language: php
matrix:
  include:
    - php: 7.2
      env: WP_VERSION=trunk WP_MULTISITE=0
    - php: 7.3
      env: WP_VERSION=trunk WP_MULTISITE=0
    - php: 7.4
      env: WP_VERSION=trunk WP_MULTISITE=0
services:
  - mysql
install:
  - composer install
  - bash tests/install-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION
script:
  - vendor/bin/phpunit
notifications:
    email: false
